### PR TITLE
Fixes #45 & #37

### LINKED ISSUE #45: awk error during get_webrtc of ios
I've pulled down the build scripts from the master branch today (so that would be commit 7570628c93). I'm trying to build for iOS. Both get_webrtc and build_webrtc are generating the message below (illegal primary in regular expression). Hopefully it's not harmful.

.....
Get the current working directory so we can change directories back when done
If no directory where depot tools should be...
Change directory into the depot tools
Pull the depot tools down to the latest
Already up-to-date.
Go back to working directory
awk: illegal primary in regular expression ) |" at  |"
 input record number 1, file 
 source line number 1
Using code signing identity
....

### PR DESCRIPTION
**Pull request by paynerc**
This fixes issue #45.

### CODE REVIEW

**Comment by paynerc** [comment]
Second commit fixes issue #37.

**Comment by thebehera** [comment]
merging and testing. will report if anything goes wrong

**Comment by paynerc** [comment]
:+1:

**Comment by thebehera** [comment]
So I'm not sure why but on my machine with the multiple codesigning certs I run into ninja errors. otherwise the running on a different machine with just one cert works fine. Here's the traceback from ninja. 
```
Traceback (most recent call last):
  File "src/webrtc/build/gyp_webrtc", line 100, in <module>
    gyp_rc = gyp.main(args)
  File "/Users/rbehera/github/webrtc-build-scripts/ios/webrtc/src/chromium/src/tools/gyp/pylib/gyp/__init__.py", line 525, in main
    return gyp_main(args)
  File "/Users/rbehera/github/webrtc-build-scripts/ios/webrtc/src/chromium/src/tools/gyp/pylib/gyp/__init__.py", line 510, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/rbehera/github/webrtc-build-scripts/ios/webrtc/src/chromium/src/tools/gyp/pylib/gyp/generator/ninja.py", line 2376, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
AssertionError: Multiple codesigning fingerprints for identity: iPhone Distribution: Pristine, Inc
Error: Command /usr/bin/python src/webrtc/build/gyp_webrtc -Dextra_gyp_flag=0 returned non-zero exit status 1 in /Users/rbehera/github/webrtc-build-scripts/ios/webrtc
Running ninja
ninja: Entering directory `out_ios_armeabi_v7a/Debug-iphoneos/'
ninja: error: build.ninja:98: unexpected EOF
  description = MERGE INFOPL
                            ^ near here
Running libtool
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Users/rbehera/github/webrtc-build-scripts/ios/webrtc/src/out_ios_armeabi_v7a/Debug-iphoneos/*.a (No such file or directory)

________ running '/usr/bin/python -c import os,sys;script = os.path.join("trunk","check_root_dir.py");_ = os.system("%s %s" % (sys.executable,script)) if os.path.exists(script) else 0' in '/Users/rbehera/github/webrtc-build-scripts/ios/webrtc'

________ running '/usr/bin/python -u src/sync_chromium.py --target-revision c086b4e24d6c6649f99743e46df87f7761dd31d1' in '/Users/rbehera/github/webrtc-build-scripts/ios/webrtc'
Chromium already up to date:  c086b4e24d6c6649f99743e46df87f7761dd31d1

________ running '/usr/bin/python src/setup_links.py' in '/Users/rbehera/github/webrtc-build-scripts/ios/webrtc'

________ running 'download_from_google_storage --directory --recursive --num_threads=10 --no_auth --bucket chromium-webrtc-resources src/resources' in '/Users/rbehera/github/webrtc-build-scripts/ios/webrtc'

________ running '/usr/bin/python src/webrtc/build/gyp_webrtc -Dextra_gyp_flag=0' in '/Users/rbehera/github/webrtc-build-scripts/ios/webrtc'
Updating projects from gyp files...
^CFailed while running "/usr/bin/python src/webrtc/build/gyp_webrtc -Dextra_gyp_flag=0"
Traceback (most recent call last):
  File "/Users/rbehera/github/webrtc-build-scripts/ios/depot_tools/gclient.py", line 2264, in <module>
    sys.exit(Main(sys.argv[1:]))
  File "/Users/rbehera/github/webrtc-build-scripts/ios/depot_tools/gclient.py", line 2252, in Main
    return dispatcher.execute(OptionParser(), argv)
  File "/Users/rbehera/github/webrtc-build-scripts/ios/depot_tools/subcommand.py", line 245, in execute
    return command(parser, args[1:])
  File "/Users/rbehera/github/webrtc-build-scripts/ios/depot_tools/gclient.py", line 2088, in CMDrunhooks
    return client.RunOnDeps('runhooks', args)
  File "/Users/rbehera/github/webrtc-build-scripts/ios/depot_tools/gclient.py", line 1528, in RunOnDeps
    self.RunHooksRecursively(self._options)
  File "/Users/rbehera/github/webrtc-build-scripts/ios/depot_tools/gclient.py", line 983, in RunHooksRecursively
    hook, cwd=self.root.root_dir, always=True)
  File "/Users/rbehera/github/webrtc-build-scripts/ios/depot_tools/gclient_utils.py", line 293, in CheckCallAndFilterAndHeader
    return CheckCallAndFilter(args, **kwargs)
  File "/Users/rbehera/github/webrtc-build-scripts/ios/depot_tools/gclient_utils.py", line 514, in CheckCallAndFilter
    in_byte = kid.stdout.read(1)
```

**Comment by paynerc** [comment]
Hrm. I am not seeing that issue. I have 11 certs come up when I run security find-identity -v.

My environment is:

OS X: 10.10.1 (14B25)
Xcode: Version 6.1.1 (6A2008a)
awk: version 20070501

What are you running?

**Comment by thebehera** [comment]
OSX: 10.9.5
Xcode: 6.1.1 (6A2008a)
awk version 20070501

looks like i need to update to yosemite *sigh*

**Comment by paynerc** [comment]
Or we could do some version detection... If running >= 10.10 do the one thing, otherwise do the other?

**Comment by thebehera** [comment]
thanks btw! the DRY was really needed but got lazy. My other machine seems to be working ok now during the compiliation. 
I think im gonna stick to updating the osx for now thanks!

**Comment by paynerc** [comment]
No worries. I had been maintaining my own script to do this building and stumbled upon yours and figured it was better for the community to switch. The last thing I am doing is adding a function to create the "framework" structure for simple drag and drop of the headers and static library for inclusion into Xcode projects. Cleaning that up presently and adding to my fork. If you are interested I can make a PR for that. If not, no worries. :)

**Comment by thebehera** [comment]
absolutely you should add that as a Pull request for those who do not want to use cocoapods

**Pull request merged**
