### PR TITLE
allow customization of GYP_DEFINES

### PR DESCRIPTION
**Pull request by RishatShamsutdinov**

### CODE REVIEW

**Comment by ArikYa** [comment]
I'm not familiar with the iOS settings for GYP_DEFINES, but there might be a conflict between the default value and the customized value

**Comment by RishatShamsutdinov** [comment]
```
#!/bin/bash

WEBRTC_RELEASE=true
GYP_DEFINES="use_openssl=1 build_with_chromium=0 ios_deployment_target=8.3 clang_xcode=1"

source ./webrtc-build-scripts/ios/dance.sh
```

I have no conflicts here.

**Comment by ArikYa** [comment]
Isn't there any chance someone will want to use "chromium_ios_signing=1" ?

**Comment by RishatShamsutdinov** [comment]
It's problem of such people.

**Comment by ArikYa** [comment]
So I can't accept the pull request, just use your own forked version

**Pull request closed without merging**
